### PR TITLE
Generate Docs with Typedoc and it's Docusaurus Markdown Plugin

### PR DESCRIPTION
**Pull request by rryter**
This does not yet automatically integrate the docs into the docs-website. 

There are still some Docusaurus things we need to figure out:

- Multi-Instances on the docs-website
- Versioning with Multi-Instances

@Hugoo is aware of these things.

Refs:
https://typedoc.org/
https://github.com/tgreyuk/typedoc-plugin-markdown/tree/master/packages/docusaurus-plugin-typedoc

### CODE REVIEW

**Comment by rryter** [comment]
I just realized the 40k added lines come from the latest `npm` version (7.18.1). I have to read up on it, but essentially we might want to "lock" the `npm` and `node` version so everybody is going to be on the same page.

**Comment by Hugoo** [comment]
I would suggest to close this PR and rather merge this one:
https://github.com/ERC725Alliance/erc725.js/pull/24

Probably the code refactor included in this PR can come in another PR

**Comment by rryter** [comment]
I'll create a new PR once #24 is merged. Did you copy and paste my stuff by hand selectively or what was your workflow on your fork?

**Comment by Hugoo** [comment]
> I'll create a new PR once #24 is merged. Did you copy and paste my stuff by hand selectively or what was your workflow on your fork?

yes just copy/pasted the TypeDoc comments, could not cp specific commit because it was too big and included other stuff

**Pull request closed without merging**
