### PR TITLE
Docs via Typedoc

### PR DESCRIPTION
**Pull request by rryter**
Merged PR from @Hugoo into `feature/docs` and added the "lost" pages again. The docs are available in the `docs` folder now.

Example: https://github.com/ERC725Alliance/erc725.js/blob/c4f88a97536bb88538a926b94a54d4f5f16d4d6a/docs/getting-started.md

### CODE REVIEW

**Comment by rryter** [comment]
@frozeman 
> How will this be imported to our docs, and how can we add custom pages, like a getting started?
Can you show me and example page?

As of right now it's a manual copy and paste of the docs directory into the appropriate directory on the `docs-website` repository. We will automate that.

You can find and example of a custom page here:
https://github.com/ERC725Alliance/erc725.js/blob/c4f88a97536bb88538a926b94a54d4f5f16d4d6a/docs/getting-started.md

**Comment by Hugoo** [comment]
Lgtm !

**Comment by rryter** [comment]
I'm going to merge this into develop, so that I can reformat the code with prettier, current formatting is not to my liking at all.

**Review by robertdavid010 — COMMENTED** [review]
LGTM as just formatting changes.

**Pull request merged**
